[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "preprocess-buffer-service"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24",
    "confluent-kafka>=2.3.0",
    "pydantic>=2.0",
]
